//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.FileWriterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileWriterService.IFileWriteService")]
    public interface IFileWriteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileWriteService/WriteInFile", ReplyAction="http://tempuri.org/IFileWriteService/WriteInFileResponse")]
        void WriteInFile(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileWriteService/WriteInFile", ReplyAction="http://tempuri.org/IFileWriteService/WriteInFileResponse")]
        System.Threading.Tasks.Task WriteInFileAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileWriteServiceChannel : WPF.FileWriterService.IFileWriteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileWriteServiceClient : System.ServiceModel.ClientBase<WPF.FileWriterService.IFileWriteService>, WPF.FileWriterService.IFileWriteService {
        
        public FileWriteServiceClient() {
        }
        
        public FileWriteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileWriteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileWriteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileWriteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteInFile(string data) {
            base.Channel.WriteInFile(data);
        }
        
        public System.Threading.Tasks.Task WriteInFileAsync(string data) {
            return base.Channel.WriteInFileAsync(data);
        }
    }
}
