//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/DataLayer")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AlterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.ServiceReference1.PersonenDetails PersonenDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Alter {
            get {
                return this.AlterField;
            }
            set {
                if ((this.AlterField.Equals(value) != true)) {
                    this.AlterField = value;
                    this.RaisePropertyChanged("Alter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.ServiceReference1.PersonenDetails PersonenDetails {
            get {
                return this.PersonenDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonenDetailsField, value) != true)) {
                    this.PersonenDetailsField = value;
                    this.RaisePropertyChanged("PersonenDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonenDetails", Namespace="http://schemas.datacontract.org/2004/07/DataLayer")]
    [System.SerializableAttribute()]
    public partial class PersonenDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlutgruppeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.ServiceReference1.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WohnortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> isEinLangerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Blutgruppe {
            get {
                return this.BlutgruppeField;
            }
            set {
                if ((object.ReferenceEquals(this.BlutgruppeField, value) != true)) {
                    this.BlutgruppeField = value;
                    this.RaisePropertyChanged("Blutgruppe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.ServiceReference1.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wohnort {
            get {
                return this.WohnortField;
            }
            set {
                if ((object.ReferenceEquals(this.WohnortField, value) != true)) {
                    this.WohnortField = value;
                    this.RaisePropertyChanged("Wohnort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> isEinLanger {
            get {
                return this.isEinLangerField;
            }
            set {
                if ((this.isEinLangerField.Equals(value) != true)) {
                    this.isEinLangerField = value;
                    this.RaisePropertyChanged("isEinLanger");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMeinTollerService")]
    public interface IMeinTollerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeinTollerService/getPersonen", ReplyAction="http://tempuri.org/IMeinTollerService/getPersonenResponse")]
        System.Collections.ObjectModel.ObservableCollection<WPF.ServiceReference1.Person> getPersonen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeinTollerService/getPersonen", ReplyAction="http://tempuri.org/IMeinTollerService/getPersonenResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WPF.ServiceReference1.Person>> getPersonenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeinTollerService/getPersonenBeschreibung", ReplyAction="http://tempuri.org/IMeinTollerService/getPersonenBeschreibungResponse")]
        System.Collections.ObjectModel.ObservableCollection<Shared.PersonenBeschreibung> getPersonenBeschreibung();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeinTollerService/getPersonenBeschreibung", ReplyAction="http://tempuri.org/IMeinTollerService/getPersonenBeschreibungResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Shared.PersonenBeschreibung>> getPersonenBeschreibungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeinTollerService/deleteById", ReplyAction="http://tempuri.org/IMeinTollerService/deleteByIdResponse")]
        void deleteById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeinTollerService/deleteById", ReplyAction="http://tempuri.org/IMeinTollerService/deleteByIdResponse")]
        System.Threading.Tasks.Task deleteByIdAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeinTollerServiceChannel : WPF.ServiceReference1.IMeinTollerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeinTollerServiceClient : System.ServiceModel.ClientBase<WPF.ServiceReference1.IMeinTollerService>, WPF.ServiceReference1.IMeinTollerService {
        
        public MeinTollerServiceClient() {
        }
        
        public MeinTollerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeinTollerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeinTollerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeinTollerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WPF.ServiceReference1.Person> getPersonen() {
            return base.Channel.getPersonen();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WPF.ServiceReference1.Person>> getPersonenAsync() {
            return base.Channel.getPersonenAsync();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Shared.PersonenBeschreibung> getPersonenBeschreibung() {
            return base.Channel.getPersonenBeschreibung();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<Shared.PersonenBeschreibung>> getPersonenBeschreibungAsync() {
            return base.Channel.getPersonenBeschreibungAsync();
        }
        
        public void deleteById(string Id) {
            base.Channel.deleteById(Id);
        }
        
        public System.Threading.Tasks.Task deleteByIdAsync(string Id) {
            return base.Channel.deleteByIdAsync(Id);
        }
    }
}
