//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonenDetails
    {
        public System.Guid Id { get; set; }
        public string Wohnort { get; set; }
        public string Blutgruppe { get; set; }
        public Nullable<int> isEinLanger { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
